# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nLUiG737BJIYj60CpOzUAB3rO9RCP_8o
"""

R1 = float(input("Enter R1 value: "))
R2 = float(input("Enter R2 value: "))

total = R1 + R2

p1 = R1 / total
p2 = R2 / total
print("\n total=",total)
print("p1 =", p1)
print("P1 Percentage =",p1*100,"%")
print("p2 =", p2)
print("P2 Percentage =",p2*100,"%")
print("p1 + p2 =", p1 + p2)

def is_safe(vertex, color, graph, colors):
    """Check whether assigning 'color' to vertex is safe."""
    for neighbor in range(len(graph)):
        if graph[vertex][neighbor] == 1 and colors[neighbor] == color:
            return False
    return True


def graph_coloring_util(vertex, graph, num_colors, colors):
    """Backtracking function to color the graph."""
    n = len(graph)

    # All vertices are colored
    if vertex == n:
        return True

    # Try every color
    for color in range(1, num_colors + 1):
        if is_safe(vertex, color, graph, colors):
            colors[vertex] = color

            if graph_coloring_util(vertex + 1, graph, num_colors, colors):
                return True

            # Backtrack
            colors[vertex] = 0

    return False


def minimum_coloring(graph):
    """Find the minimum number of colors needed."""
    n = len(graph)

    # Try 1, 2, 3, ... colors
    for num_colors in range(1, n + 1):
        colors = [0] * n

        if graph_coloring_util(0, graph, num_colors, colors):
            return num_colors, colors

    return n, colors

# Tic-Tac-Toe using Minimax Algorithm

# Print the board
def print_board(board):
    print()
    for i in range(3):
        print(" " + " | ".join(board[i * 3:(i + 1) * 3]))
        if i < 2:
            print("---+---+---")
    print()


# Check if there is a winner
def check_winner(board):
    winning_positions = [
        (0, 1, 2),
        (3, 4, 5),
        (6, 7, 8),
        (0, 3, 6),
        (1, 4, 7),
        (2, 5, 8),
        (0, 4, 8),
        (2, 4, 6)
    ]

    for a, b, c in winning_positions:
        if board[a] == board[b] == board[c] and board[a] != " ":
            return board[a]

    return None


# Check whether the board is full
def is_full(board):
    return " " not in board


# Minimax algorithm
def minimax(board, is_maximizing):
    winner = check_winner(board)

    # Terminal states
    if winner == "O":
        return 1
    elif winner == "X":
        return -1
    elif is_full(board):
        return 0

    # Computer's turn - maximize score
    if is_maximizing:
        best_score = -float("inf")

        for i in range(9):
            if board[i] == " ":
                board[i] = "O"

                score = minimax(board, False)

                board[i] = " "
                best_score = max(best_score, score)

        return best_score

    # Human's turn - minimize score
    else:
        best_score = float("inf")

        for i in range(9):
            if board[i] == " ":
                board[i] = "X"

                score = minimax(board, True)

                board[i] = " "
                best_score = min(best_score, score)

        return best_score


# Find the best move for the computer
def best_move(board):
    best_score = -float("inf")
    move = -1

    for i in range(9):
        if board[i] == " ":
            board[i] = "O"

            score = minimax(board, False)

            board[i] = " "

            if score > best_score:
                best_score = score
                move = i

    return move


# Main game
def play_game():
    board = [" "] * 9

    print("TIC-TAC-TOE")
    print("You are X. Computer is O.")
    print("Enter a position from 1 to 9:")
    print()
    print(" 1 | 2 | 3")
    print("---+---+---")
    print(" 4 | 5 | 6")
    print("---+---+---")
    print(" 7 | 8 | 9")

    while True:
        print_board(board)

        # Human move
        while True:
            try:
                position = int(input("Enter your move (1-9): ")) - 1

                if position < 0 or position > 8:
                    print("Please enter a number between 1 and 9.")
                elif board[position] != " ":
                    print("That position is already occupied.")
                else:
                    board[position] = "X"
                    break

            except ValueError:
                print("Please enter a valid number.")

        # Check human win
        if check_winner(board) == "X":
            print_board(board)
            print("You win!")
            break

        # Check draw
        if is_full(board):
            print_board(board)
            print("It's a draw!")
            break

        # Computer move
        print("Computer is thinking...")
        move = best_move(board)
        board[move] = "O"

        # Check computer win
        if check_winner(board) == "O":
            print_board(board)
            print("Computer wins!")
            break

        # Check draw
        if is_full(board):
            print_board(board)
            print("It's a draw!")
            break


# Start the game
play_game()

# How Minimax works
# The algorithm considers **all possible future moves**:
# * **Computer (O)** tries to maximize the score.
# * **Human (X)** tries to minimize the score.
# * `+1` -> Computer wins
# * `-1` -> Human wins
# * `0` -> Draw
# The computer recursively explores possible moves until the game reaches a win, loss, or draw, then works backward to select the best move.
# Because Tic-Tac-Toe has only 9 squares, this basic Minimax implementation is fast enough to play perfectly.

def print_board(board):
    print()
    for i in range(3):
        print(" " + " | ".join(board[i * 3:(i + 1) * 3]))
        if i < 2:
            print("---+---+---")
    print()


# Check if there is a winner
def check_winner(board):
    winning_positions = [
        (0, 1, 2),
        (3, 4, 5),
        (6, 7, 8),
        (0, 3, 6),
        (1, 4, 7),
        (2, 5, 8),
        (0, 4, 8),
        (2, 4, 6)
    ]

    for a, b, c in winning_positions:
        if board[a] == board[b] == board[c] and board[a] != " ":
            return board[a]

    return None


# Check whether the board is full
def is_full(board):
    return " " not in board


# Minimax algorithm
def minimax(board, is_maximizing):
    winner = check_winner(board)

    # Terminal states
    if winner == "O":
        return 1
    elif winner == "X":
        return -1
    elif is_full(board):
        return 0

    # Computer's turn - maximize score
    if is_maximizing:
        best_score = -float("inf")

        for i in range(9):
            if board[i] == " ":
                board[i] = "O"

                score = minimax(board, False)

                board[i] = " "
                best_score = max(best_score, score)

        return best_score

    # Human's turn - minimize score
    else:
        best_score = float("inf")

        for i in range(9):
            if board[i] == " ":
                board[i] = "X"

                score = minimax(board, True)

                board[i] = " "
                best_score = min(best_score, score)

        return best_score


# Find the best move for the computer
def best_move(board):
    best_score = -float("inf")
    move = -1

    for i in range(9):
        if board[i] == " ":
            board[i] = "O"

            score = minimax(board, False)

            board[i] = " "

            if score > best_score:
                best_score = score
                move = i

    return move


# Main game
def play_game():
    board = [" "] * 9

    print("TIC-TAC-TOE")
    print("You are X. Computer is O.")
    print("Enter a position from 1 to 9:")
    print()
    print(" 1 | 2 | 3")
    print("---+---+---")
    print(" 4 | 5 | 6")
    print("---+---+---")
    print(" 7 | 8 | 9")

    while True:
        print_board(board)

        # Human move
        while True:
            try:
                position = int(input("Enter your move (1-9): ")) - 1

                if position < 0 or position > 8:
                    print("Please enter a number between 1 and 9.")
                elif board[position] != " ":
                    print("That position is already occupied.")
                else:
                    board[position] = "X"
                    break

            except ValueError:
                print("Please enter a valid number.")

        # Check human win
        if check_winner(board) == "X":
            print_board(board)
            print("You win!")
            break

        # Check draw
        if is_full(board):
            print_board(board)
            print("It's a draw!")
            break

        # Computer move
        print("Computer is thinking...")
        move = best_move(board)
        board[move] = "O"

        # Check computer win
        if check_winner(board) == "O":
            print_board(board)
            print("Computer wins!")
            break

        # Check draw
        if is_full(board):
            print_board(board)
            print("It's a draw!")
            break



def is_safe(vertex, color, graph, colors):
    """Check whether assigning 'color' to vertex is safe."""
    for neighbor in range(len(graph)):
        if graph[vertex][neighbor] == 1 and colors[neighbor] == color:
            return False
    return True


def graph_coloring_util(vertex, graph, num_colors, colors):
    """Backtracking function to color the graph."""
    n = len(graph)

    # All vertices are colored
    if vertex == n:
        return True

    # Try every color
    for color in range(1, num_colors + 1):
        if is_safe(vertex, color, graph, colors):
            colors[vertex] = color

            if graph_coloring_util(vertex + 1, graph, num_colors, colors):
                return True

            # Backtrack
            colors[vertex] = 0

    return False


def minimum_coloring(graph):
    """Find the minimum number of colors needed."""
    n = len(graph)

    # Try 1, 2, 3, ... colors
    for num_colors in range(1, n + 1):
        colors = [0] * n

        if graph_coloring_util(0, graph, num_colors, colors):
            return num_colors, colors

    return n, colors

def is_safe(vertex, color, graph, colors):
    """Check whether assigning 'color' to vertex is safe."""
    for neighbor in range(len(graph)):
        if graph[vertex][neighbor] == 1 and colors[neighbor] == color:
            return False
    return True


def graph_coloring_util(vertex, graph, num_colors, colors):
    """Backtracking function to color the graph."""
    n = len(graph)

    # All vertices are colored
    if vertex == n:
        return True

    # Try every color
    for color in range(1, num_colors + 1):
        if is_safe(vertex, color, graph, colors):
            colors[vertex] = color

            if graph_coloring_util(vertex + 1, graph, num_colors, colors):
                return True

            # Backtrack
            colors[vertex] = 0

    return False


def minimum_coloring(graph):
    """Find the minimum number of colors needed."""
    n = len(graph)

    # Try 1, 2, 3, ... colors
    for num_colors in range(1, n + 1):
        colors = [0] * n

        if graph_coloring_util(0, graph, num_colors, colors):
            return num_colors, colors

    return n, colors